limit_req_zone $binary_remote_addr zone=one:10m rate=120r/m;
limit_conn_zone $binary_remote_addr zone=addr:10m;

server {
    listen 80;
    server_name FileServer;

    location / {
        return 301 https://$host$request_uri;
    }
}


upstream gunicorn {
    server unix:/run/gunicorn.sock fail_timeout=0;
}

server {
    listen 443 ssl;
    server_name FileServer;

    http2 on;

    ssl_certificate /app/cert/root.pem;
    ssl_certificate_key /app/cert/root-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    keepalive_timeout 6;

    # root /app/storage;

    location /storage/ {
        internal;
        alias /app/storage/;
    }

    location / {
        proxy_pass http://gunicorn;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        limit_req zone=one burst=30;
        limit_conn addr 30;

        client_max_body_size 16384m;
    }
}
