import os
import base64
import hashlib
import logging

logging.basicConfig(level=logging.WARNING)

# EVERY PATH MUST BE ENDED WITH os.sep

SERVER_PATH = os.path.dirname(os.path.abspath(__file__)) + "/"
MAIN_PATH = SERVER_PATH + '../'
STATIC_PATH = SERVER_PATH + 'static/'
STORAGE_PATH = MAIN_PATH + 'storage/'
UPLOAD_TMP_PATH = STORAGE_PATH + 'tmp/'
DATABASE_FILENAME = STORAGE_PATH + 'database.sqlite3'

USERS_HOME_STORAGE = 'upload'
HOME_CAP_NAME = 'Home'
BACKUP_PREFIX = 'backup'
TRIVIAL_BACKUPS = os.getenv('TRIVIAL_BACKUPS', 'FALSE').upper() == 'TRUE'
ALLOW_LINKS = os.getenv('ALLOW_LINKS', 'FALSE').upper() == 'TRUE'
SHOW_BACKUPS_IN_FILES = os.getenv('SHOW_BACKUPS_IN_FILES', 'FALSE').upper() == 'TRUE'

DEFAULT_ADMIN_NAME = 'admin'
DEFAULT_ADMIN_PASSWORD = 'admin'
FAIL_LOGIN_DELAY_TIME = 10
MINIMUM_TOKEN_LENGTH = 8


USE_X_ACCEL_REDIRECT = os.getenv('USE_X_ACCEL_REDIRECT', 'FALSE').upper() == 'TRUE'
INCLUDE_STATIC = os.getenv('INCLUDE_STATIC', 'TRUE').upper() == 'TRUE'
BUFFER_SIZE = 256*1024
MAX_DOWNLOAD_RATE = 64*1024*1024
LAZY_LOADING_SIZE = 4*1024*1024
SESSION_CLEANUP_INTERVAL = 3600
SESSION_EXPIRES = 3600*24*7
SESSION_DIR = "/tmp/flask_sessions"
COMPRESSION_TIMEOUT = 36*3600

MAX_FORM_PARTS = 16*1024
MAX_FORM_MEMORY_SIZE = 64*1024
MAX_CONTENT_LENGTH = 16*1024*1024*1024

