import os
import base64
import hashlib
import logging

logging.basicConfig(level=logging.WARNING)

# EVERY PATH MUST BE ENDED WITH os.sep

SERVER_PATH = os.path.dirname(os.path.abspath(__file__)) + "/"
MAIN_PATH = SERVER_PATH + '../'
CERT_PATH = MAIN_PATH + 'cert/'
STATIC_PATH = SERVER_PATH + 'static/'
STORAGE_PATH = MAIN_PATH + 'storage/'
UPLOAD_PATH = STORAGE_PATH + 'upload/'
DATABASE_FILENAME = STORAGE_PATH + 'database.sqlite3'

BACKUP_PREFIX = 'backup'
ALLOW_LINKS = False
SHOW_BACKUPS_IN_FILES = False

DEFAULT_ADMIN_NAME = 'admin'
DEFAULT_ADMIN_PASSWORD = 'admin'
FAIL_LOGIN_DELAY_TIME = 10
MINIMUM_TOKEN_LENGTH = 8


USE_X_ACCEL_REDIRECT = os.getenv('USE_X_ACCEL_REDIRECT', 'FALSE').upper() == 'TRUE'
INCLUDE_STATIC = True
BUFFER_SIZE = 256*1024
MAX_DOWNLOAD_RATE = 64*1024*1024
LAZY_LOADING_SIZE = 4*1024*1024
SESSION_CLEANUP_INTERVAL = 3600
SESSION_EXPIRES = 3600*24*7
SESSION_DIR = "/tmp/flask_sessions"
COMPRESSION_TIMEOUT = 36*3600

